
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://yttpgzcpqvaommiistyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0dHBnemNwcXZhb21taWlzdHljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODI1MzYsImV4cCI6MjA2NTY1ODUzNn0.fyAUklRh41eWLmT8Sohimq1BZIuTIfb6rsCq3Ju9urc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
